name: Build SM64 para Switch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Restaurar ROM original
      run: |
        mv baserom.us.z64.zip baserom.us.z64

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y git make python3 unzip wget build-essential

    - name: Instalar devkitPro
      run: |
        wget -O - https://apt.devkitpro.org/install-devkitpro-pacman | sudo bash
        sudo dkp-pacman -S --noconfirm switch-dev devkitA64 libnx switch-sdl2

    - name: Configurar entorno
      run: |
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITA64=/opt/devkitpro/devkitA64" >> $GITHUB_ENV
        echo "/opt/devkitpro/tools/bin:/opt/devkitpro/devkitA64/bin" >> $GITHUB_PATH

    - name: Compilar juego
      run: |
        make TARGET_SWITCH=1

    - name: Subir el NRO
      uses: actions/upload-artifact@v4
      with:
        name: sm64-switch-port
        path: build/us_nx/sm64.us.f3dex2e.nro
